# aarch64: configure Hyprland for ARM hardware
#
# ARM systems (VMs with virtio-gpu, Apple Silicon, RPi, etc.) need
# specific workarounds for Hyprland's DRM/GPU subsystem:
#
# 1. AQ_NO_ATOMIC=1 — many ARM DRM drivers lack full atomic modesetting support
# 2. render { explicit_sync = 0 } — broken on split-node GPU topology (most ARM GPUs)
# 3. GSK_RENDERER=ngl — default GSK renderer crashes GTK apps on aarch64
#
# References:
#   https://github.com/hyprwm/Hyprland/issues/9404
#   https://github.com/hyprwm/Hyprland/issues/10401
#   https://github.com/hyprwm/Hyprland/discussions/10530
#   https://github.com/hyprwm/aquamarine/blob/main/docs/env.md

if [[ "$(uname -m)" != "aarch64" ]]; then
  return 0
fi

echo "aarch64 detected — configuring Hyprland for ARM hardware..."

# --- 1. Clean stale/wrong env vars from previous installs ---
# Earlier versions incorrectly set WLR_RENDERER=pixman and LIBGL_ALWAYS_SOFTWARE=1.
# These BREAK Hyprland: aquamarine ignores WLR_RENDERER entirely, and
# LIBGL_ALWAYS_SOFTWARE forces llvmpipe when Hyprland requires hardware OpenGL.
for stale_var in WLR_RENDERER LIBGL_ALWAYS_SOFTWARE WLR_NO_HARDWARE_CURSORS; do
  sudo sed -i "/^${stale_var}=/d" /etc/environment 2>/dev/null || true
done

for uwsm_file in "$HOME/.config/uwsm/env" "$HOME/.config/uwsm/env-hyprland"; do
  if [[ -f "$uwsm_file" ]]; then
    sed -i '/WLR_RENDERER/d; /LIBGL_ALWAYS_SOFTWARE/d; /WLR_NO_HARDWARE_CURSORS/d' "$uwsm_file"
    sed -i '/# aarch64: software rendering/d' "$uwsm_file"
  fi
done

# --- 2. Set AQ_NO_ATOMIC in /etc/environment (fallback for non-wrapper launches) ---
sudo sed -i '/^AQ_NO_ATOMIC=/d' /etc/environment 2>/dev/null || true
echo "AQ_NO_ATOMIC=1" | sudo tee -a /etc/environment >/dev/null

# --- 3. Hyprland config: aarch64-specific render and env settings ---
mkdir -p "$HOME/.config/hypr"
cat > "$HOME/.config/hypr/aarch64.conf" <<'EOF'
# aarch64: ARM-specific Hyprland settings
# Generated by omarchy install/config/hardware/aarch64-vm.sh

# Fix GTK apps on aarch64 (protocol error with default GSK renderer)
# https://github.com/hyprwm/Hyprland/discussions/10530
env = GSK_RENDERER,ngl
EOF

# Source aarch64.conf from hyprland.conf (idempotent)
HYPRCONF="$HOME/.config/hypr/hyprland.conf"
if [[ -f "$HYPRCONF" ]] && ! grep -q 'aarch64\.conf' "$HYPRCONF"; then
  printf '\n# aarch64: ARM-specific render settings\nsource = ~/.config/hypr/aarch64.conf\n' >> "$HYPRCONF"
fi

# --- 4. Hyprland wrapper (sets aarch64 env vars, then uses start-hyprland) ---
# AQ env vars must be set BEFORE Hyprland starts (aquamarine reads them at init).
# We set them here, then delegate to start-hyprland for proper uwsm session management.
sudo tee /usr/local/bin/hyprland-direct >/dev/null <<'WRAPPER'
#!/bin/bash
# aarch64: set ARM-specific env vars, then launch via start-hyprland
# AQ_NO_ATOMIC: disable DRM atomic modesetting (not fully supported by many ARM drivers)
export AQ_NO_ATOMIC=1
# Uncomment if display fails to initialize (virtio-gpu, older ARM SoCs):
# export AQ_NO_MODIFIERS=1
exec start-hyprland "$@"
WRAPPER
sudo chmod +x /usr/local/bin/hyprland-direct

# --- 5. SDDM session entry ---
sudo tee /usr/share/wayland-sessions/hyprland-direct.desktop >/dev/null <<'EOF'
[Desktop Entry]
Name=Hyprland (Direct)
Comment=Hyprland compositor via start-hyprland with aarch64 env vars
Exec=/usr/local/bin/hyprland-direct
Type=Application
EOF

# --- 6. Ensure user has DRM device access (Hyprland #8908) ---
if ! groups "$USER" | grep -q '\bvideo\b'; then
  sudo usermod -aG video "$USER"
  echo "Added $USER to video group for DRM device access"
fi

echo "aarch64 Hyprland configuration complete"
